### ISSUE TITLE
Unit testing infrastructure

### ISSUE THREAD

**Issue by dakotablair** [kbase-sfa-2021/example_sdk_app#2]
We wish to add unit testing which can be done offline, that is, without contacting KBase directly.

Goals:
- Use an active testing library, i.e. not `nose`.
- Have a `Makefile` directive that allows the user to launch a test either from their host or a container.
- Have `kb-sdk test` not break on unit tests
   - Possible solution: create a new `unit-test` directory.

**Comment by bio-boris** [comment]
* Replace nose with pytest in the makefile, so you don't have to worry about breaking on unit-tests
* Solved 1 and 3

**Comment by dakotablair** [comment]
How can we make the developer experience easier?

Ideally, one could simply run `make unit-tests` and run the unit tests based on the code on the host machine. If the tests depend on system dependencies within the image this can be a problem. Running the tests within a container solves this problem, but creates another since the container filesystem is different than the host. If the tests change on the host then the image needs to be rebuilt before tests can run. One alternative is to mount a volume, but this might may require modifying `run_bash.sh`.

**Comment by bio-boris** [comment]
* We created a single make command to run unit tests via docker, (it runs the latest tests with a bind mount instead of rebuilding the image, however it requires an additional script)
* Can we reduce the number of make directives in order to run the test?

**Comment by dakotablair** [comment]
Closed by #3 .
